// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encode() -> AnyObject
}

class Response<T> {
    let statusCode: Int
    let header: [String: String]
    let body: T

    init(statusCode: Int, header: [String: String], body: T) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    convenience init(response: NSHTTPURLResponse, body: T) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for (key, value) in rawHeader {
            header[key as! String] = value as? String
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

private var once = dispatch_once_t()
class Decoders {
    static private var decoders = Dictionary<String, ((AnyObject) -> AnyObject)>()
    
    static func addDecoder<T>(#clazz: T.Type, decoder: ((AnyObject) -> T)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0) as! AnyObject }
    }
    
    static func decode<T>(#clazz: [T].Type, source: AnyObject) -> [T] {
        let array = source as! [AnyObject]
        return array.map { Decoders.decode(clazz: T.self, source: $0) }
    }
    
    static func decode<T, Key: Hashable>(#clazz: [Key:T].Type, source: AnyObject) -> [Key:T] {
        let sourceDictinoary = source as! [Key: AnyObject]
        var dictionary = [Key:T]()
        for (key, value) in sourceDictinoary {
            dictionary[key] = Decoders.decode(clazz: T.self, source: value)
        }
        return dictionary
    }
    
    static func decode<T>(#clazz: T.Type, source: AnyObject) -> T {
        initialize()
        if source is T {
            return source as! T
        }
        
        let key = "\(T.self)"
        if let decoder = decoders[key] {
           return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decodeOptional<T>(#clazz: T.Type, source: AnyObject?) -> T? {
        if source is NSNull {
            return nil
        }
        return source.map { (source: AnyObject) -> T in
            Decoders.decode(clazz: clazz, source: source)
        }
    }

    static func decodeOptional<T>(#clazz: [T].Type, source: AnyObject?) -> [T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static func decodeOptional<T, Key: Hashable>(#clazz: [Key:T].Type, source: AnyObject?) -> [Key:T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [Key:T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }
	
    static private func initialize() {
        dispatch_once(&once) {
            let dateTimeFormatter = NSDateFormatter()
            dateTimeFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss'Z'"
            let dateFormatter = NSDateFormatter()
            dateFormatter.dateFormat = "yyyy-MM-dd"
            // Decoder for NSDate
            Decoders.addDecoder(clazz: NSDate.self) { (source: AnyObject) -> NSDate in
                let sourceString = source as! String
                if count(sourceString) == 10 {
                    return dateFormatter.dateFromString(sourceString)!
                }
                return dateTimeFormatter.dateFromString(sourceString)!
            } 

			// Decoder for Job
            Decoders.addDecoder(clazz: Job.self) { (source: AnyObject) -> Job in
                let sourceDictionary = source as! [NSObject:AnyObject]
                var instance = Job()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"])
                instance.token = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["token"])
                instance.type = (sourceDictionary["type"] as? String).map { Job.Type(rawValue: $0)! }! 
                instance.status = Decoders.decodeOptional(clazz: Status.self, source: sourceDictionary["status"])
                instance.process = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["process"])
                instance.conversion = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["conversion"])
                instance.input = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["input"])
                instance.callback = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["callback"])
                instance.server = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["server"])
                instance.created_at = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["created_at"])
                instance.modified_at = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["modified_at"])
                return instance
            }
			

			// Decoder for InputFile
            Decoders.addDecoder(clazz: InputFile.self) { (source: AnyObject) -> InputFile in
                let sourceDictionary = source as! [NSObject:AnyObject]
                var instance = InputFile()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"])
                instance.type = (sourceDictionary["type"] as? String).map { InputFile.Type(rawValue: $0)! } 
                instance.source = Decoders.decode(clazz: String.self, source: sourceDictionary["source"]!)
                instance.filename = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["filename"])
                instance.size = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["size"])
                instance.created_at = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["created_at"])
                instance.modified_at = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["modified_at"])
                return instance
            }
			

			// Decoder for OutputFile
            Decoders.addDecoder(clazz: OutputFile.self) { (source: AnyObject) -> OutputFile in
                let sourceDictionary = source as! [NSObject:AnyObject]
                var instance = OutputFile()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"])
                instance.source = Decoders.decode(clazz: AnyObject.self, source: sourceDictionary["source"]!)
                instance.uri = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["uri"])
                instance.filename = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["filename"])
                instance.size = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["size"])
                instance.created_at = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["created_at"])
                return instance
            }
			

			// Decoder for Conversion
            Decoders.addDecoder(clazz: Conversion.self) { (source: AnyObject) -> Conversion in
                let sourceDictionary = source as! [NSObject:AnyObject]
                var instance = Conversion()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"])
                instance.target = Decoders.decode(clazz: String.self, source: sourceDictionary["target"]!)
                instance.category = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["category"])
                instance.options = Decoders.decodeOptional(clazz: AnyObject.self, source: sourceDictionary["options"])
                return instance
            }
			

			// Decoder for Thread
            Decoders.addDecoder(clazz: Thread.self) { (source: AnyObject) -> Thread in
                let sourceDictionary = source as! [NSObject:AnyObject]
                var instance = Thread()
                instance.hash = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["hash"])
                instance.status = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["status"])
                instance.info = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["info"])
                instance.created_at = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["created_at"])
                instance.modified_at = Decoders.decodeOptional(clazz: NSDate.self, source: sourceDictionary["modified_at"])
                return instance
            }
			

			// Decoder for Status
            Decoders.addDecoder(clazz: Status.self) { (source: AnyObject) -> Status in
                let sourceDictionary = source as! [NSObject:AnyObject]
                var instance = Status()
                instance.code = Decoders.decode(clazz: String.self, source: sourceDictionary["code"]!)
                instance.info = Decoders.decode(clazz: String.self, source: sourceDictionary["info"]!)
                return instance
            }
			

			// Decoder for Error
            Decoders.addDecoder(clazz: Error.self) { (source: AnyObject) -> Error in
                let sourceDictionary = source as! [NSObject:AnyObject]
                var instance = Error()
                instance.code = Decoders.decodeOptional(clazz: Int.self, source: sourceDictionary["code"])
                instance.message = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["message"])
                instance.errors = Decoders.decodeOptional(clazz: AnyObject.self, source: sourceDictionary["errors"])
                return instance
            }
			
        }
    }
}
