//
// Conversion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class Conversion: JSONEncodable {

    /** Identifier for the job conversion. */
    var id: String?
    /** Identifier for the job conversion type. */
    var target: String!
    /** Category for the conveted file. */
    var category: String?
    /** Type of conversion to perform with the file. */
    var options: AnyObject?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["target"] = self.target
        nillableDictionary["category"] = self.category
        nillableDictionary["options"] = self.options?.encode()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
