//
// InputFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class InputFile: JSONEncodable {

    enum Type: String { 
        case Upload = "upload"
        case Remote = "remote"
        case Output = "output"
    }
    
    /** Unique identifier for the file. */
    var id: String?
    /** How the file has been generated. */
    var type: Type?
    /** The source of the file to be used that can be either, an external url. An identifier for an uploaded file to the server or an identifier for another job. */
    var source: String!
    /** Filename of the file. */
    var filename: String?
    /** Size of the file in bytes. */
    var size: Int?
    /** Date and time when the job was created. */
    var created_at: NSDate?
    /** Date and time when the job was last modified. */
    var modified_at: NSDate?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["source"] = self.source
        nillableDictionary["filename"] = self.filename
        nillableDictionary["size"] = self.size
        nillableDictionary["created_at"] = self.created_at?.encode()
        nillableDictionary["modified_at"] = self.modified_at?.encode()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
