//
// OutputFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class OutputFile: JSONEncodable {

    /** Unique identifier for the file. */
    var id: String?
    /** Sources for the files including the input files and conversion used. */
    var source: AnyObject!
    /** Url for downloading the file. */
    var uri: String?
    /** Filename of the file. */
    var filename: String?
    /** Size of the file in bytes. */
    var size: Int?
    /** Date and time when the job was created. */
    var created_at: NSDate?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["source"] = self.source.encode()
        nillableDictionary["uri"] = self.uri
        nillableDictionary["filename"] = self.filename
        nillableDictionary["size"] = self.size
        nillableDictionary["created_at"] = self.created_at?.encode()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
