//
// Thread.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class Thread: JSONEncodable {

    /** Unique identifier of the thread. */
    var hash: String?
    /** Status of the thread. */
    var status: Int?
    /** Extra information. */
    var info: String?
    /** Date and time when the job was created. */
    var created_at: NSDate?
    /** Date and time when the job was last modified. */
    var modified_at: NSDate?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["hash"] = self.hash
        nillableDictionary["status"] = self.status
        nillableDictionary["info"] = self.info
        nillableDictionary["created_at"] = self.created_at?.encode()
        nillableDictionary["modified_at"] = self.modified_at?.encode()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
